Merged revisions 2605-2729 via svnmerge from https://software.sandia.gov/svn/public/coopr/coopr.opt/trunk
........
  r2613 | jwatson | 2010-05-10 16:31:00 -0600 (Mon, 10 May 2010) | 3 lines
  
  Adding documentation of semantics to some of the solver results object components.
........
  r2616 | wehart | 2010-05-12 10:04:50 -0600 (Wed, 12 May 2010) | 2 lines
  
  Bug fix:  setting 'suffixes' attribute instead of '_suffixes'
........
  r2617 | wehart | 2010-05-12 17:42:43 -0600 (Wed, 12 May 2010) | 2 lines
  
  Bug fix:  specify default parameters using class scoping.
........
  r2633 | jwatson | 2010-05-24 20:23:09 -0600 (Mon, 24 May 2010) | 3 lines
  
  Added warm_start_capable method definition to the IOptSolver interface. Was previously only in the OptSolver class interface.
........
  r2657 | prsteel | 2010-06-14 15:58:18 -0600 (Mon, 14 Jun 2010) | 9 lines
  
  Changes to coopr.opt to support SOS constraints.
  
  Added function 'has_capability' to 'OptSolve', the generic base class
  for all solvers. Accepts a string 'st', and returns true if
  self._capabilities[st] == True, and False otherwise. Derived classes are
  responsible for overriding the contents of self._capabilities.
........
  r2667 | prsteel | 2010-06-16 12:45:58 -0600 (Wed, 16 Jun 2010) | 8 lines
  
  Added empty capabilities dict to 'OptSolver' base class.
  
  Before, the base class did not define self._capabilities, and so would
  throw an error when 'has_capabilities' was called. OptSolver now
  defines an empty self._capabilities container to avoid this.
........
  r2671 | prsteel | 2010-06-17 12:35:42 -0600 (Thu, 17 Jun 2010) | 8 lines
  
  Altered solver.py and convert.py to more directly pass solver
  capabilities to the solver writers.
  
  This should fix the bug that has been causing the error
  "AttributeError: 'Model' object has no attribute 'has_capability'"
........
  r2673 | wehart | 2010-06-19 20:56:19 -0600 (Sat, 19 Jun 2010) | 3 lines
  
  Allow the value of 'options' to be passed in as None without generating an
  error.
........
  r2675 | wehart | 2010-06-19 21:42:21 -0600 (Sat, 19 Jun 2010) | 5 lines
  
  Resolving test failures due to r2671.  The API for IProblemConverter 
  needed to be generalized in a consistent manner.
  
  Also, the convert_problem API doesn't _really_ need to have has_capability argument, so I set a default for this.
........
  r2682 | wehart | 2010-06-20 08:43:20 -0600 (Sun, 20 Jun 2010) | 3 lines
  
  Misc change to I/O.  Conditionally print timing for 
  the results reader output.
........
  r2700 | prsteel | 2010-06-22 11:07:54 -0600 (Tue, 22 Jun 2010) | 5 lines
  
  Temporary fix.
  
  Pyomo fails if the CooprMIPTestDriver plugin is loaded; we prevent it from loading.
........
  r2701 | wehart | 2010-06-22 13:07:13 -0600 (Tue, 22 Jun 2010) | 2 lines
  
  Undoing Pat's hack.  I hope I've worked-around the issues he was seeing.
........
  r2703 | wehart | 2010-06-22 13:17:26 -0600 (Tue, 22 Jun 2010) | 2 lines
  
  Portability fix for Python 2.5
........
  r2714 | wehart | 2010-06-26 14:52:43 -0600 (Sat, 26 Jun 2010) | 3 lines
  
  This subpackage is depricated.  I've deleted the functionality that has
  moved into pyutilib.misc.
........
  r2715 | wehart | 2010-06-26 14:53:24 -0600 (Sat, 26 Jun 2010) | 5 lines
  
  Added a method to extract a YAML representation of a
  results object.
  
  Print out infinities with YAML-compliant format.
........