Altered solver.py and convert.py to more directly pass solver capabilities to the solver writers.
This should fix the bug that has been causing the error
"AttributeError: 'Model' object has no attribute 'has_capability'"